FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["MGH.ApiDocker/MGH.ApiDocker.csproj", "MGH.ApiDocker/"]
RUN dotnet restore "MGH.ApiDocker/MGH.ApiDocker.csproj"
COPY . .
WORKDIR "/src/MGH.ApiDocker"
RUN dotnet build "MGH.ApiDocker.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MGH.ApiDocker.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MGH.ApiDocker.dll"]
