name: "Publish"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]



jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Build
        run: dotnet build Core/MGH.Core.Domain/MGH.Core.Domain.csproj
      - name: Pack
        run: dotnet pack Core/MGH.Core.Domain/MGH.Core.Domain.csproj --configuration Release --no-restore --output ./nugetPackages
      - name: Publish
        run: dotnet nuget push "./nugetPackages/*.nupkg"  -k ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json --skip-duplicate
        
        
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Build
        run: dotnet build Core/MGH.Core.Persistence/MGH.Core.Persistence.csproj
      - name: Pack
        run: dotnet pack Core/MGH.Core.Persistence/MGH.Core.Persistence.csproj --configuration Release --no-restore --output ./nugetPackages
      - name: Publish
        run: dotnet nuget push "./nugetPackages/*.nupkg"  -k ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json --skip-duplicate


      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Build
        run: dotnet build Core/MGH.Core.Infrastructure/MGH.Core.Infrastructure.csproj
      - name: Pack
        run: dotnet pack Core/MGH.Core.Infrastructure/MGH.Core.Infrastructure.csproj --configuration Release --no-restore --output ./nugetPackages
      - name: Publish
        run: dotnet nuget push "./nugetPackages/*.nupkg"  -k ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json --skip-duplicate
  



  


    


    
          
          
          
          
          
          
          
          
          
          
          
          
          
          # dotnet version 6.x
          # - uses: actions/checkout@v3
          # - uses: actions/setup-dotnet@v3
          # with:
          # dotnet-version: '6.0.x'
          # - name: Build
          # run: dotnet build MGH.Swagger/MGH.Swagger.csproj
          # - name: Pack
          # run: dotnet pack MGH.Swagger/MGH.Swagger.csproj --configuration Release --no-restore --output ./nugetPackages
          # - name: Publish
          # run: dotnet nuget push "./nugetPackages/*.nupkg"  -k ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json --skip-duplicate
          
          # - uses: actions/checkout@v3
          # - uses: actions/setup-dotnet@v3
          # with:
          # dotnet-version: '6.0.x'
          # - name: Build
          # run: dotnet build MGH.DevExtreme/MGH.DevExtreme.csproj
          # - name: Pack
          # run: dotnet pack MGH.DevExtreme/MGH.DevExtreme.csproj --configuration Release --no-restore --output ./nugetPackages
          # - name: Publish
          # run: dotnet nuget push "./nugetPackages/*.nupkg"  -k ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json --skip-duplicate
          
          # - uses: actions/checkout@v3
          # - uses: actions/setup-dotnet@v3
          # with:
          # dotnet-version: '6.0.x'
          # - name: Build
          # run: dotnet build MGH.Exceptions/MGH.Exceptions.csproj
          # - name: Pack
          # run: dotnet pack MGH.Exceptions/MGH.Exceptions.csproj --configuration Release --no-restore --output ./nugetPackages
          # - name: Publish
          # run: dotnet nuget push "./nugetPackages/*.nupkg"  -k ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json --skip-duplicate
          
          # - uses: actions/checkout@v3
          # - uses: actions/setup-dotnet@v3
          # with:
          # dotnet-version: '7.0.x'
          # - name: Build
          # run: dotnet build MGH.EntityFramework/MGH.EntityFramework.csproj
          # - name: Pack
          # run: dotnet pack MGH.EntityFramework/MGH.EntityFramework.csproj --configuration Release --no-restore --output ./nugetPackages
          # - name: Publish
          # run: dotnet nuget push "./nugetPackages/*.nupkg"  -k ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json --skip-duplicate
          
          
          # - uses: actions/checkout@v3
          # - uses: actions/setup-dotnet@v3
          # with:
          # dotnet-version: '6.0.x'
          # - name: Build
          # run: dotnet build MGH.Extensions/MGH.Extensions.csproj
          # - name: Pack
          # run: dotnet pack MGH.Extensions/MGH.Extensions.csproj --configuration Release --no-restore --output ./nugetPackages
        # - name: Publish
        # run: dotnet nuget push "./nugetPackages/*.nupkg"  -k ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json --skip-duplicate


